import Head from 'next/head'
import Image from 'next/image'
import Card from '../components/card'
import Header from '../components/header'
import styles from '../styles/Home.module.css'
import Container from '../components/container'
import Script from 'next/script'

export default function Home() {
  // (() => {
  //   document.querySelector('video').playbackRate = 0.5;

  // })()
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main className={styles.main}>
        <Container><Card /><Card /></Container>

        <video autoPlay loop muted id='video' className={styles.video}>
          <source src='/mundo.mp4' type='video/mp4' />
        </video>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/logo_white_color.png" alt="Core Infra Logo" width={72} height={16} />
          </span>
        </a>
      </footer>

      <Script src="https://chat.api.milvus.com.br/apichat/widget/script/a3c0438052/d7b736ea334ba0e9e3c3f3a35854640e4c543216c7733658db923ee1e2d700667ba0e69a84b5ebe22e2b79592dfd4af3aeb837e960ede882087de5456c91d11c5568ee186fe1959da015efb7f387ea7f978ecd11c2d3d27c077509ee18e3f1a9d96e611a92"></Script>

    </div>
  )
}
